# Generated by Django 5.2.6 on 2025-09-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_memory',
            old_name='content',
            new_name='requests',
        ),
        migrations.RenameField(
            model_name='chat_memory',
            old_name='sender',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='chat_memory',
            name='receiver',
        ),
        migrations.AddField(
            model_name='chat_memory',
            name='reponse_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='chat_memory',
            name='response_text',
            field=models.TextField(null=True),
        ),
    ]
