# Generated by Django 5.2.6 on 2025-09-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_content_chat_memory_requests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_memory',
            old_name='reponse_image',
            new_name='response_image',
        ),
    ]
